---
runtime: shiny
---

```{css style, echo=F}
.shiny-frame {
  height: 1450px;
}
```

```{r, include=F}

library(tidyverse)
library(plotly)
library(igraph)
library(ggraph)
library(cowplot)
library(stringr)
library(zoo)
library(DT)

theme_set(theme_minimal())

```

```{r, include=F}

competitions <- read_csv('data/competitions.csv') %>% select(-1)

matches <- read_csv('data/matches.csv') %>% select(-1)

teams <- read_csv('data/teams.csv') %>% select(-1)

players <- read_csv('data/players.csv') %>% 
  select(-1) %>%
  mutate(
    name = stringi::stri_unescape_unicode(name),
    shortName = stringi::stri_unescape_unicode(shortName),
    teamId = as.double(teamId),
    foot = case_when(
      foot == "right" ~ "Right",
      foot == "left" ~ "Left",
      foot == "both" ~ "Both",
      TRUE ~ "NA"
    )
  )

home_color <- "#3E9ACC"
away_color <- "#D36135"

```

```{r, include=F}
# Plot the soccer pitch
plot_pitch <- function() {
  # Sequences for penalty arcs
  right_arc_angle <- acos((87.5 - 93.5) / 9.15)
  right_arc_seq <- seq(right_arc_angle, 2 * pi - right_arc_angle, length.out = 100)
  left_arc_angle <- acos((16.5 - 10.5) / 9.15)
  left_arc_seq <- seq(left_arc_angle, -left_arc_angle, length.out = 100)
  
  # Create pitch elements
  list(
    # Outer lines
    geom_rect(aes(xmin = 0, xmax = 104, ymin = 0, ymax = 68), color = "#faf0e6", fill = NA, inherit.aes = FALSE),
    # Goal boxes
    geom_rect(aes(xmin = 87.5, xmax = 104, ymin = 13.84, ymax = 54.16), color = "#faf0e6", fill = NA, inherit.aes = FALSE),
    geom_rect(aes(xmin = 0, xmax = 16.5, ymin = 13.84, ymax = 54.16), color = "#faf0e6", fill = NA, inherit.aes = FALSE),
    # 6-yard boxes
    geom_rect(aes(xmin = 99.5, xmax = 104, ymin = 24.84, ymax = 43.16), color = "#faf0e6", fill = NA, inherit.aes = FALSE),
    geom_rect(aes(xmin = 0, xmax = 4.5, ymin = 24.84, ymax = 43.16), color = "#faf0e6", fill = NA, inherit.aes = FALSE),
    # Halfway line
    geom_segment(aes(x = 52, y = 0, xend = 52, yend = 68), color = "#faf0e6", inherit.aes = FALSE),
    # Penalty spots
    geom_point(aes(x = 93, y = 34), color = "#faf0e6", size = 1, inherit.aes = FALSE),
    geom_point(aes(x = 11, y = 34), color = "#faf0e6", size = 1, inherit.aes = FALSE),
    # Center circle
    geom_point(aes(x = 52, y = 34), color = "#faf0e6", inherit.aes = FALSE),
    annotate(
      "path", 
      x = 52 + 9.15 * cos(seq(0, 2 * pi, length.out = 100)), 
      y = 34 + 9.15 * sin(seq(0, 2 * pi, length.out = 100)), 
      color = "#faf0e6"
    ),
     # Right penalty arc
    annotate(
      "path", 
      x = 93.5 + 9.15 * cos(right_arc_seq), 
      y = 34 + 9.15 * sin(right_arc_seq), 
      color = "#faf0e6"
    ),
    # Left penalty arc
    annotate(
      "path", 
      x = 10.5 + 9.15 * cos(left_arc_seq), 
      y = 34 + 9.15 * sin(left_arc_seq), 
      color = "#faf0e6"
    ),
    # Set plot limits and remove plot expansion
    coord_fixed(),
    scale_x_continuous(limits = c(0, 104), expand = c(.02, .02)),
    scale_y_continuous(limits = c(0, 68), expand = c(.02, .02))
  )
}

```

```{r, include=F}
# Create plot of all events for a match
match_event_plot <- function(match_id, matches, players, teams, player_list = NULL) {
  # Get info for match
  match_info <- matches %>% filter(id == match_id)
  
  # Read in events table
  match_events <- read_csv(paste0('data/events/', match_id, '.csv')) %>% select(-1)

  # Get dataframes for each team
  home_team <- match_events %>%
    filter(teamId == match_info$home_team) %>%
    mutate(
      x = x * 104 / 100,
      y = y * 68 / 100
    ) %>%
    left_join(players %>% select(id, shortName, position, foot), by = c("playerId" = "id")) %>%
    left_join(teams %>% select(id, name), by = c("teamId" = "id"))
  
  away_team <- match_events %>%
    filter(teamId == match_info$away_team) %>%
    mutate(
      x = x * 104 / 100,
      y = y * 68 / 100
    ) %>%
    left_join(players %>% select(id, shortName, position, foot), by = c("playerId" = "id")) %>%
    left_join(teams %>% select(id, name), by = c("teamId" = "id"))
  
  # Filter to selected players
  if (!is.null(player_list)) {
    home_team <- home_team %>% filter(playerId %in% player_list)
    away_team <- away_team %>% filter(playerId %in% player_list)
  }
  
  # Create interactive plot
  ggplotly(
    ggplot() + 
      # Add pitch lines
      plot_pitch() + 
      # Team 1 data
      geom_point(data = home_team, aes(x = x, y = y), color = 'black', shape = 16) +
      geom_point(data = home_team, aes(x = x, y = y, text = (paste0(
        'Event: ', eventName, '\n',
        'Team: ', name, '\n',
        'Player: ', shortName, '\n',
        'Position: ', position, '\n',
        'Foot: ', foot, '\n'
      ))), color = home_color, shape = 16, size = 1.45) +
      # Team 2 data
      geom_point(data = away_team, aes(x = x, y = y), color = 'black', shape = 16) +
      geom_point(data = away_team, aes(x = x, y = y, text = (paste0(
        'Event: ', eventName, '\n',
        'Team: ', name, '\n',
        'Player: ', shortName, '\n',
        'Position: ', position, '\n',
        'Foot: ', foot, '\n'
      ))), color = away_color, shape = 16, size = 1.45) +
      # Theme information
      theme(
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.grid = element_blank(),
        plot.background = element_rect(fill = "#195905"),
        plot.margin = margin(0, 0, 0, 0)
      ),
    tooltip = 'text'
  ) %>% layout(
    # Specify layout for plotly object
    margin = list(r = 20),
    plot_bgcolor = '#195905'
  )
}

```

```{r, include=F}
# Get table of player ids, name, and position for a specified match and side
get_match_players <- function(match_id, side, matches, players) {
  # Get match info and events
  match_info <- matches %>% filter(id == match_id)
  match_events <- read_csv(paste0('data/events/', match_id, '.csv')) %>% select(-1)
  
  # Get id for either home or away team
  if (side == "Home") {
    team_id <- match_info$home_team
  } else {
    team_id <- match_info$away_team
  }
  
  # Get all players from events data
  players <- match_events %>%
    filter(teamId == team_id) %>%
    .$playerId %>%
    unique() %>%
    data.frame(id = .) %>%
    filter(id != 0) %>%
    left_join(players %>% select(id, shortName, position), by = "id") %>%
    mutate(lastName = if_else(str_detect(shortName, " "), 
                              str_extract(shortName, "(?<=\\s).*$"), shortName)) %>%
    arrange(lastName)
  
  # Set column name depending on side
  if (side == "Home") {
    players <- players %>% select(id, Home = lastName, Position = position)
  } else {
    players <- players %>% select(id, Away = lastName, Position = position)
  }
  
  return(players)
}

```

```{r, include=F}
# Create network plot for team passing
make_pass_network <- function(passing, color) {
  # Get all unique vertices
  vertices <- passing %>%
    select(sender, name) %>% 
    distinct()
  
  # Rename to match igraph's requirements
  vertices <- vertices %>%
    rename(id = sender)
  
  # Create network object
  g <- graph_from_data_frame(d = passing, directed = FALSE, vertices = vertices)
  
  # Make network plot
  set.seed(35)
  ggraph(g, layout = "fr") + 
    geom_edge_link(aes(width = Time, alpha = Time), lineend = 'round') + 
    geom_node_point(aes(size = degree(g, mode = "all")), color = color) + 
    geom_node_text(aes(label = name), vjust = 0.5, hjust = 0.5) +
    scale_edge_width(range = c(0.05, 1)) + 
    scale_size_continuous(range = c(5, 20)) + 
    scale_edge_alpha(range = c(0.5, 1), guide = 'none') + 
    theme(legend.position = "none")
}

# Load data and create passing networks
passing_network <- function(match_id, players) {
  # Load passing datasets for specified match
  passing_home <- read_csv(paste0('data/passing/', match_id, '_home.csv')) %>% 
    select(-1) %>%
    left_join(players %>% select(id, shortName), by = c("sender" = "id")) %>%
    separate(
      shortName, into = c("firstName", "lastName"), 
      sep = " ", extra = "merge", fill = "right"
    ) %>%
    mutate(name = if_else(is.na(lastName), firstName, lastName)) %>%
    select(-firstName, -lastName)
  
  passing_away <- read_csv(paste0('data/passing/', match_id, '_away.csv')) %>% 
    select(-1) %>%
    left_join(players %>% select(id, shortName), by = c("sender" = "id")) %>%
    separate(
      shortName, into = c("firstName", "lastName"), 
      sep = " ", extra = "merge", fill = "right"
    ) %>%
    mutate(name = if_else(is.na(lastName), firstName, lastName)) %>%
    select(-firstName, -lastName)
  
  # Get network graphs for each team
  network_home <- make_pass_network(passing_home, home_color)
  network_away <- make_pass_network(passing_away, away_color)

  # Combine networks horizontally
  plot_grid(network_home, network_away, align = "h", ncol = 2)
}

```

```{r, include=F}
# Create invasion plot
invasion_plot <- function(match_id) {
  # Load invasion datasets for specified match
  invasion_home <- read_csv(paste0('data/invasion/', match_id, '_home.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Invasion_RA = rollapply(Invasion, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  invasion_away <- read_csv(paste0('data/invasion/', match_id, '_away.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Invasion_RA = rollapply(Invasion, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  # Load acceleration datasets for specified match
  acceleration_home <- read_csv(paste0('data/acceleration/', match_id, '_home.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Acceleration_RA = rollapply(Acceleration, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  acceleration_away <- read_csv(paste0('data/acceleration/', match_id, '_away.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Acceleration_RA = rollapply(Acceleration, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  # Create ggplot object
  invasion_plot <- ggplotly(
    ggplot() + 
      geom_line(data = invasion_home, aes(x = Time, y = Invasion_RA), color = home_color) + 
      geom_line(data = invasion_away, aes(x = Time, y = Invasion_RA), color = away_color) + 
      labs(y = "Invasion Index")
  )
  
  # Create ggplot object
  acceleration_plot <- ggplotly(
    ggplot() + 
      geom_line(data = acceleration_home, aes(x = Time, y = Acceleration_RA), color = home_color) + 
      geom_line(data = acceleration_away, aes(x = Time, y = Acceleration_RA), color = away_color) + 
      labs(y = "Acceleration Index")
  )
  
  # Align the plots horizontally
  subplot(invasion_plot, acceleration_plot, nrows = 1, margin = 0.05) %>%
    layout(
      xaxis = list(title = "Time (min)"),
      yaxis = list(title = "Invasion Index"),
      xaxis2 = list(title = "Time (min)"),
      yaxis2 = list(title = "Acceleration Index")
    )
}

```

```{r, echo=F, message=F, warning=F, error=F}
# UI layout
ui <- fluidPage(
  tags$head(
    tags$style(HTML("
      /* Adjust the style for the title */
      #matchTitle {
        font-weight: bold;
        font-size: 22px;
        text-align: center;
      }
      /* Adjust the size and padding of the table cells */
      .dataTables_wrapper .dataTable td {
        padding: 3px;
        font-size: 12px;
      }
      /* Hide the table header */
      .dataTables_wrapper .dataTable thead {
        display: none;
      }
    "))
  ),
  titlePanel("Soccer Match Dashboard"),
  # Match id entry box and submit button
  fluidRow(
    column(2, textInput("match_id", "Match ID:", value = "2576335")),
    column(2, actionButton("submit", "Submit", style = "margin-top: 25px; margin-left: -25px;"))
  ),
  # Pitch plot title
  fluidRow(
    column(12, textOutput("matchTitle"))
  ),
  # Event pitch plot with player lists
  fluidRow(
    column(2, dataTableOutput("homePlayers")),
    column(8, plotlyOutput("pitchPlot", height = "400px")),
    column(2, dataTableOutput("awayPlayers"))
  ),
  # Passing network title
  fluidRow(
    column(12, align = "center", tags$h2(
      "Team Passing Networks", 
      style = "font-weight: bold; text-align: center; margin-top: -10px; margin-bottom: 10px; font-size: 18px;"
    ))
  ),
  # Passing network plot
  fluidRow(
    column(12, plotOutput("passingPlot", height = "400px")),
  ),
  # Invasion/acceleration title
  fluidRow(
    column(12, align = "center", tags$h2(
      "Invasion & Acceleration Plots", 
      style = "font-weight: bold; text-align: center; margin-bottom: -2px; font-size: 18px;"
    ))
  ),
  # Invasion/acceleration plots
  fluidRow(
    column(12, plotlyOutput("invasionPlot", height = "350px"))
  )
)

# Server logic
server <- function(input, output, session) {
  # Reactive value to store selected match ID
  selected_match_id <- reactiveVal(2576335)
  
  # Observe event for the submit button
  observeEvent(input$submit, {
    selected_match_id(input$match_id)
  })
  
  # Reactive expression for the match title
  match_title <- reactive({
    req(selected_match_id())
    matches %>%
      filter(id == selected_match_id()) %>%
      pull(label)
  })

  # Render the match title
  output$matchTitle <- renderText({
    match_title()
  })
  
  # Reactive data for home player table
  home_players <- reactive({
    req(selected_match_id())
    get_match_players(selected_match_id(), "Home", matches, players)
  })

  # Reactive data for away player table
  away_players <- reactive({
    req(selected_match_id())
    get_match_players(selected_match_id(), "Away", matches, players)
  })
  
  # Combined reactive expression for selected player ids
  selected_player_ids <- reactive({
    # Start with all players from both teams
    combined_ids <- c(home_players()$id, away_players()$id)
    
    # If players are selected in either table, filter to those players
    if (length(input$homePlayers_rows_selected) > 0 | length(input$awayPlayers_rows_selected) > 0) {
      combined_ids <- c(
        home_players()$id[input$homePlayers_rows_selected],
        away_players()$id[input$awayPlayers_rows_selected]
      )
    }
    
    # Return the combined selected ids
    return(combined_ids)
  })
  
  # Event match plot
  output$pitchPlot <- renderPlotly({
    req(selected_match_id())
    # Use the combined selected player IDs
    match_event_plot(selected_match_id(), matches, players, teams, selected_player_ids())
  })
  
  # Table of home players
  output$homePlayers <- renderDataTable({
    datatable(
      home_players() %>% select(-id),
      rownames = FALSE,
      caption = htmltools::tags$caption(
        style = 'caption-side: top; text-align: center; font-weight: bold;',
        'Home Players'
      ),
      options = list(
        paging = FALSE,
        searching = FALSE,
        info = FALSE,
        ordering = FALSE,
        autoWidth = TRUE
      ),
      class = 'cell-border compact'
    )
  }, selection = 'none')

  # Table of away players
  output$awayPlayers <- renderDataTable({
    datatable(
      away_players() %>% select(-id),
      rownames = FALSE,
      caption = htmltools::tags$caption(
        style = 'caption-side: top; text-align: center; font-weight: bold;',
        'Away Players'
      ),
      options = list(
        paging = FALSE,
        searching = FALSE,
        info = FALSE,
        ordering = FALSE,
        autoWidth = TRUE
      ),
      class = 'cell-border compact'
    )
  }, selection = 'none')

  # Passing network plots
  output$passingPlot <- renderPlot({
    req(selected_match_id())
    passing_network(selected_match_id(), players)
  })
  
  # Match invasion plot
  output$invasionPlot <- renderPlotly({
    req(selected_match_id())
    invasion_plot(selected_match_id())
  })
}

# Run the application
shinyApp(ui = ui, server = server)

```


