
### Packages and Data

```{r, include=F}

library(tidyverse)
library(plotly)
library(igraph)
library(ggraph)
library(cowplot)
library(zoo)
library(stringr)

theme_set(theme_minimal())

```

```{r, include=F}

competitions <- read_csv('data/competitions.csv') %>% select(-1)

matches <- read_csv('data/matches.csv') %>% select(-1)

teams <- read_csv('data/teams.csv') %>% 
  select(-1) %>%
  mutate(name = stringi::stri_unescape_unicode(name))

players <- read_csv('data/players.csv') %>% 
  select(-1) %>%
  mutate(
    name = stringi::stri_unescape_unicode(name),
    shortName = stringi::stri_unescape_unicode(shortName),
    teamId = as.double(teamId),
    foot = case_when(
      foot == "right" ~ "Right",
      foot == "left" ~ "Left",
      foot == "both" ~ "Both",
      TRUE ~ "NA"
    )
  )

home_color <- "#3E9ACC"
away_color <- "#D36135"

```

### Title

```{r}
# Function to return title for a match
get_match_label <- function(matches, match_id) {
  # Get home team id
  home_team <- matches %>% filter(id == match_id) %>% pull(home_team)
  
  # Get initial match label
  match_label <- matches %>% filter(id == match_id) %>% pull(label)

  # Get team names and final score
  team_names <- str_extract_all(match_label, "[A-Za-z]+(?:\\s[A-Za-z]+)*")[[1]]
  scores <- as.numeric(str_extract_all(match_label, "\\d+")[[1]])
  
  # Determine which team is home and away
  match_info <- data.frame(
    team = team_names,
    score = scores,
    stringsAsFactors = FALSE
  ) %>%
    left_join(teams %>% select(name, id), by = c("team" = "name")) %>%
    select(id, team, score) %>%
    mutate(side = ifelse(id == home_team, "H", "A"))
  
  # Create title
  paste0(
    match_info$team[1], " (", match_info$side[1], ") - ", 
    match_info$team[2], " (", match_info$side[2], "), ", 
    match_info$score[1], " - ", match_info$score[2]
  )
}

get_match_label(matches, 2565829)

```

```{r}
# Stratified sampling for match ids from each competition
set.seed(35)
match_list <- matches %>% 
  group_by(competitionId) %>%
  sample_n(size = round(250 * n() / nrow(matches))) %>%
  ungroup() %>%
  pull(id) %>%
  append(c(2576335, 2576105, 2576263)) %>%
  unique() %>%
  data.frame(id = .) %>%
  write_csv('data/match_ids.csv')

```

### Event Distribution

```{r}

events %>% 
  filter(matchId == 2576335) %>%
  group_by(eventName) %>%
  summarize(count = n(), .groups = 'drop') %>%
  arrange(desc(count)) %>%
  ggplot(aes(x = reorder(eventName, count), y = count)) + 
    geom_col() + 
    coord_flip()

```

### Invasion Plot

```{r, message=F}
# Create invasion plot
invasion_plot <- function(match_id) {
  # Load invasion datasets for specified match
  invasion_home <- read_csv(paste0('data/invasion/', match_id, '_home.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Invasion_RA = rollapply(Invasion, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  invasion_away <- read_csv(paste0('data/invasion/', match_id, '_away.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Invasion_RA = rollapply(Invasion, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  # Load acceleration datasets for specified match
  acceleration_home <- read_csv(paste0('data/acceleration/', match_id, '_home.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Acceleration_RA = rollapply(Acceleration, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  acceleration_away <- read_csv(paste0('data/acceleration/', match_id, '_away.csv')) %>%
    select(-1) %>%
    mutate(
      Time = Time / 60,
      Acceleration_RA = rollapply(Acceleration, width = 220, FUN = mean, fill = NA, align = "right", partial = TRUE)
    )
  
  # Create ggplot object
  invasion_plot <- ggplotly(
    ggplot() + 
      geom_line(data = invasion_home, aes(x = Time, y = Invasion_RA), color = home_color) + 
      geom_line(data = invasion_away, aes(x = Time, y = Invasion_RA), color = away_color) + 
      labs(y = "Invasion Index")
  )
  
  # Create ggplot object
  acceleration_plot <- ggplotly(
    ggplot() + 
      geom_line(data = acceleration_home, aes(x = Time, y = Acceleration_RA), color = home_color) + 
      geom_line(data = acceleration_away, aes(x = Time, y = Acceleration_RA), color = away_color) + 
      labs(y = "Acceleration Index")
  )
  
  # Align the plots horizontally
  subplot(invasion_plot, acceleration_plot, nrows = 1, margin = 0.05) %>%
    layout(
      yaxis = list(title = "Invasion Index"),
      yaxis2 = list(title = "Acceleration Index")
    )
}

invasion_plot(2576335)

```

### Pass Network

```{r}
# Create network plot for team passing
make_pass_network <- function(passing, color) {
  # Get all unique vertices
  vertices <- passing %>%
    select(sender, name) %>% 
    distinct()
  
  # Rename to match igraph's requirements
  vertices <- vertices %>%
    rename(id = sender)
  
  # Create network object
  g <- graph_from_data_frame(d = passing, directed = FALSE, vertices = vertices)
  
  # Make network plot
  set.seed(35)
  ggraph(g, layout = "fr") + 
    geom_edge_link(aes(width = Time, alpha = Time), lineend = 'round') + 
    geom_node_point(aes(size = degree(g, mode = "all")), color = color) + 
    geom_node_text(aes(label = name), vjust = 0.5, hjust = 0.5) +
    scale_edge_width(range = c(0.05, 1)) + 
    scale_size_continuous(range = c(5, 20)) + 
    scale_edge_alpha(range = c(0.5, 1), guide = 'none') + 
    theme(legend.position = "none")
}

# Load data and create passing networks
passing_network <- function(match_id, players) {
  # Get ids for both teams
  match_info <- matches %>%
    filter(id == match_id) %>%
    select(id, team1, team2)
  team1 <- match_info$team1
  team2 <- match_info$team2
  
  # Load passing datasets for specified match
  passing_home <- read_csv(paste0('data/passing/', match_id, '_home.csv')) %>% 
    select(-1) %>%
    left_join(players %>% select(id, shortName), by = c("sender" = "id")) %>%
    separate(
      shortName, into = c("firstName", "lastName"), 
      sep = " ", extra = "merge", fill = "right"
    ) %>%
    mutate(name = if_else(is.na(lastName), firstName, lastName)) %>%
    select(-firstName, -lastName)
  
  passing_away <- read_csv(paste0('data/passing/', match_id, '_away.csv')) %>% 
    select(-1) %>%
    left_join(players %>% select(id, shortName), by = c("sender" = "id")) %>%
    separate(
      shortName, into = c("firstName", "lastName"), 
      sep = " ", extra = "merge", fill = "right"
    ) %>%
    mutate(name = if_else(is.na(lastName), firstName, lastName)) %>%
    select(-firstName, -lastName)
  
  # Get network graphs for each team
  network_home <- make_pass_network(passing_home, home_color)
  network_away <- make_pass_network(passing_away, away_color)

  # Combine networks horizontally
  plot_grid(network_home, network_away, align = "h", ncol = 2)
}

passing_network(2576335, players)

```

### Team Table

```{r, message=F}
# Get table of player ids, name, and position for a specified match and side
get_match_players <- function(match_id, side, matches, players) {
  # Get match info and events
  match_info <- matches %>% filter(id == match_id)
  match_events <- read_csv(paste0('data/events/', match_id, '.csv')) %>% select(-1)
  
  # Get id for either home or away team
  if (side == "home") {
    team_id <- match_info$home_team
  } else {
    team_id <- match_info$away_team
  }
  
  # Get all players from events data
  match_events %>%
    filter(teamId == team_id) %>%
    .$playerId %>%
    unique() %>%
    data.frame(id = .) %>%
    filter(id != 0) %>%
    left_join(players %>% select(id, shortName, position), by = "id") %>%
    mutate(lastName = if_else(str_detect(shortName, " "), 
                              str_extract(shortName, "(?<=\\s).*$"), shortName)) %>%
    arrange(lastName) %>%
    select(id, name = shortName, position)
}

get_match_players(2517000, "away", matches, players)

```





